#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CarmeraUseRecipe.Resource", IsApplication=true)]

namespace CarmeraUseRecipe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int Title = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int editText1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int editText2 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int imageView1 = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int myButton = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int email = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int openCamera = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int save_face = 2130968579;
			
<<<<<<< HEAD
=======
			// aapt resource value: 0x7f02004f
			public const int abc_textfield_search_right_selected_holo_dark = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int abc_textfield_search_right_selected_holo_light = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int abc_textfield_search_selected_holo_dark = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int abc_textfield_search_selected_holo_light = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int abc_textfield_searchview_holo_dark = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int abc_textfield_searchview_holo_light = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int abc_textfield_searchview_right_holo_dark = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int abc_textfield_searchview_right_holo_light = 2130837590;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a003c
			public const int Title = 2131361852;
			
			// aapt resource value: 0x7f0a001c
			public const int action_bar = 2131361820;
			
			// aapt resource value: 0x7f0a0001
			public const int action_bar_activity_content = 2131361793;
			
			// aapt resource value: 0x7f0a001b
			public const int action_bar_container = 2131361819;
			
			// aapt resource value: 0x7f0a001f
			public const int action_bar_overlay_layout = 2131361823;
			
			// aapt resource value: 0x7f0a001a
			public const int action_bar_root = 2131361818;
			
			// aapt resource value: 0x7f0a0023
			public const int action_bar_subtitle = 2131361827;
			
			// aapt resource value: 0x7f0a0022
			public const int action_bar_title = 2131361826;
			
			// aapt resource value: 0x7f0a001d
			public const int action_context_bar = 2131361821;
			
			// aapt resource value: 0x7f0a0002
			public const int action_menu_divider = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int action_menu_presenter = 2131361795;
			
			// aapt resource value: 0x7f0a0024
			public const int action_mode_close_button = 2131361828;
			
			// aapt resource value: 0x7f0a0025
			public const int activity_chooser_view_content = 2131361829;
			
			// aapt resource value: 0x7f0a000f
			public const int always = 2131361807;
			
			// aapt resource value: 0x7f0a0016
			public const int beginning = 2131361814;
			
			// aapt resource value: 0x7f0a002d
			public const int checkbox = 2131361837;
			
			// aapt resource value: 0x7f0a0010
			public const int collapseActionView = 2131361808;
			
			// aapt resource value: 0x7f0a0028
			public const int default_activity_button = 2131361832;
			
			// aapt resource value: 0x7f0a0014
			public const int dialog = 2131361812;
			
			// aapt resource value: 0x7f0a0009
			public const int disableHome = 2131361801;
			
			// aapt resource value: 0x7f0a0015
			public const int dropdown = 2131361813;
			
			// aapt resource value: 0x7f0a003d
			public const int editText1 = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int editText2 = 2131361854;
			
			// aapt resource value: 0x7f0a0030
			public const int edit_query = 2131361840;
			
			// aapt resource value: 0x7f0a0017
			public const int end = 2131361815;
			
			// aapt resource value: 0x7f0a0026
			public const int expand_activities_button = 2131361830;
			
			// aapt resource value: 0x7f0a002c
			public const int expanded_menu = 2131361836;
			
			// aapt resource value: 0x7f0a0000
			public const int home = 2131361792;
			
			// aapt resource value: 0x7f0a000a
			public const int homeAsUp = 2131361802;
			
			// aapt resource value: 0x7f0a002a
			public const int icon = 2131361834;
			
			// aapt resource value: 0x7f0a0011
			public const int ifRoom = 2131361809;
			
			// aapt resource value: 0x7f0a0027
			public const int image = 2131361831;
			
			// aapt resource value: 0x7f0a0040
			public const int imageView1 = 2131361856;
			
			// aapt resource value: 0x7f0a0006
			public const int listMode = 2131361798;
			
			// aapt resource value: 0x7f0a0029
			public const int list_item = 2131361833;
			
			// aapt resource value: 0x7f0a0018
			public const int middle = 2131361816;
			
			// aapt resource value: 0x7f0a003f
			public const int myButton = 2131361855;
			
			// aapt resource value: 0x7f0a0012
			public const int never = 2131361810;
			
			// aapt resource value: 0x7f0a0019
			public const int none = 2131361817;
			
			// aapt resource value: 0x7f0a0007
			public const int normal = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int progress_circular = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int progress_horizontal = 2131361797;
			
			// aapt resource value: 0x7f0a002f
			public const int radio = 2131361839;
			
			// aapt resource value: 0x7f0a0032
			public const int search_badge = 2131361842;
			
			// aapt resource value: 0x7f0a0031
			public const int search_bar = 2131361841;
			
			// aapt resource value: 0x7f0a0033
			public const int search_button = 2131361843;
			
			// aapt resource value: 0x7f0a0038
			public const int search_close_btn = 2131361848;
			
			// aapt resource value: 0x7f0a0034
			public const int search_edit_frame = 2131361844;
			
			// aapt resource value: 0x7f0a003a
			public const int search_go_btn = 2131361850;
			
			// aapt resource value: 0x7f0a0035
			public const int search_mag_icon = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int search_plate = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int search_src_text = 2131361847;
			
			// aapt resource value: 0x7f0a003b
			public const int search_voice_btn = 2131361851;
			
			// aapt resource value: 0x7f0a002e
			public const int shortcut = 2131361838;
			
			// aapt resource value: 0x7f0a000b
			public const int showCustom = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int showHome = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int showTitle = 2131361805;
			
			// aapt resource value: 0x7f0a001e
			public const int split_action_bar = 2131361822;
			
			// aapt resource value: 0x7f0a0039
			public const int submit_area = 2131361849;
			
			// aapt resource value: 0x7f0a0008
			public const int tabMode = 2131361800;
			
			// aapt resource value: 0x7f0a002b
			public const int title = 2131361835;
			
			// aapt resource value: 0x7f0a0020
			public const int top_action_bar = 2131361824;
			
			// aapt resource value: 0x7f0a0021
			public const int up = 2131361825;
			
			// aapt resource value: 0x7f0a000e
			public const int useLogo = 2131361806;
			
			// aapt resource value: 0x7f0a0013
			public const int withText = 2131361811;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int abc_max_action_buttons = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int abc_action_bar_decor = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int abc_action_bar_decor_include = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int abc_action_bar_decor_overlay = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int abc_action_bar_home = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int abc_action_bar_tab = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int abc_action_bar_tabbar = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int abc_action_bar_title_item = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int abc_action_bar_view_list_nav_layout = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int abc_action_menu_item_layout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int abc_action_menu_layout = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int abc_action_mode_bar = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int abc_action_mode_close_item = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int abc_activity_chooser_view = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int abc_activity_chooser_view_include = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int abc_activity_chooser_view_list_item = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int abc_expanded_menu_layout = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int abc_list_menu_item_checkbox = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int abc_list_menu_item_icon = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int abc_list_menu_item_layout = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int abc_list_menu_item_radio = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int abc_popup_menu_item_layout = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int abc_search_dropdown_item_icons_2line = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int abc_search_view = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int abc_simple_decor = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int Main = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int RecognitionPage = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int support_simple_spinner_dropdown_item = 2130968602;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0001
			public const int abc_action_bar_home_description = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int abc_action_bar_up_description = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int abc_action_menu_overflow_description = 2131427331;
			
			// aapt resource value: 0x7f0b0000
			public const int abc_action_mode_done = 2131427328;
			
			// aapt resource value: 0x7f0b000a
			public const int abc_activity_chooser_view_see_all = 2131427338;
			
			// aapt resource value: 0x7f0b0009
			public const int abc_activitychooserview_choose_application = 2131427337;
			
			// aapt resource value: 0x7f0b0006
			public const int abc_searchview_description_clear = 2131427334;
			
			// aapt resource value: 0x7f0b0005
			public const int abc_searchview_description_query = 2131427333;
			
			// aapt resource value: 0x7f0b0004
			public const int abc_searchview_description_search = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int abc_searchview_description_submit = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int abc_searchview_description_voice = 2131427336;
			
			// aapt resource value: 0x7f0b000c
			public const int abc_shareactionprovider_share_with = 2131427340;
			
			// aapt resource value: 0x7f0b000b
			public const int abc_shareactionprovider_share_with_application = 2131427339;
			
			// aapt resource value: 0x7f0b000e
			public const int app_name = 2131427342;
			
			// aapt resource value: 0x7f0b0011
			public const int email = 2131427345;
			
			// aapt resource value: 0x7f0b000d
			public const int hello = 2131427341;
			
			// aapt resource value: 0x7f0b000f
			public const int openCamera = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int save_face = 2131427344;
			
>>>>>>> a0985d0... empty class to act as face API interface
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
